### ISSUE TITLE
[Error] DKMS Build failed & [Bug] No such file or directory when trying to use in-app updater

### ISSUE THREAD

**Issue by BananaShapedGrenade** [yunusemreyl/OmenCommandCenterforLinux#203]
So, im not sure if i should report that, but every update or install ends on DKMS Build error. It works anyway after reboot, and seems fine. So i'm not completely sure if it should work like that or not, and i report it not for the first time too. 
### **[Error]:DKMS Build failed**
> =====================================
>  Installing DKMS Kernel Driver
> =====================================
> [INFO] Detected distro: manjaro
> [INFO] Installing dependencies (pacman)...
> [INFO] Detected versioned headers package: linux612-headers
> [INFO] Attempting to install: dkms linux612-headers base-devel
> warning: dkms-3.4.3-1 is up to date -- skipping
> warning: linux612-headers-6.12.108-1 is up to date -- skipping
> warning: base-devel-1-3 is up to date -- skipping
>  there is nothing to do
> [WARN] Forcing custom hp-wmi install path on kernel 6.12.108-1-MANJARO.
> [INFO] Purging stale hp-omen-extra module files...
> [INFO] Kernel 6.12.108-1-MANJARO detected (< 7.0) — installing both hp-wmi and hp-omen-extra...
> [INFO] Checking for stock hp-wmi driver path...
> [INFO] Stock driver detected at: /lib/modules/6.12.108-1-MANJARO/kernel/drivers/platform/x86/hp/hp-wmi.ko.zst
> [INFO] Installing via DKMS...
> Creating symlink /var/lib/dkms/hp-omen-extra/2.0.3/source -> /usr/src/hp-omen-extra-2.0.3
> Sign command: /usr/lib/modules/6.12.108-1-MANJARO/build/scripts/sign-file
> Signing key: /var/lib/dkms/mok.key
> Public certificate (MOK): /var/lib/dkms/mok.pub
> 
> Building module(s)...(bad exit status: 2)
> Failed command:
> grep -iq clang /proc/version && make LLVM=1 -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.3/build EXTRA_CFLAGS='' modules || make -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.3/build EXTRA_CFLAGS='' modules
> 
> Error! Bad return status for module build on kernel: 6.12.108-1-MANJARO (x86_64)
> Consult /var/lib/dkms/hp-omen-extra/2.0.3/build/make.log for more information.
> [ERROR] DKMS build failed. Check logs.

Here's the logs.

> DKMS (dkms-3.4.3) make.log for hp-omen-extra/2.0.3 for kernel 6.12.108-1-MANJARO (x86_64)
> Mon 14 Sep 01:21:47 CEST 2026
> 
> Building module(s)
> # command: grep -iq clang /proc/version && make LLVM=1 -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.3/build EXTRA_CFLAGS='' modules || make -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.3/build EXTRA_CFLAGS='' modules
> make: Entering directory '/usr/lib/modules/6.12.108-1-MANJARO/build'
> grep: dkms.conf: No such file or directory
> grep: dkms.conf: No such file or directory
>   CC [M]  /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.o
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2697:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
>  2697 |         .profile_get = platform_profile_omen_get,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2697:24: note: (near initialization for ‘platform_profile_omen_handler.profile_get’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2029:12: note: ‘platform_profile_omen_get’ declared here
>  2029 | static int platform_profile_omen_get(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2698:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
>  2698 |         .profile_set = platform_profile_omen_set,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2698:24: note: (near initialization for ‘platform_profile_omen_handler.profile_set’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2152:12: note: ‘platform_profile_omen_set’ declared here
>  2152 | static int platform_profile_omen_set(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2702:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
>  2702 |         .profile_get = platform_profile_victus_get,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2702:24: note: (near initialization for ‘platform_profile_victus_handler.profile_get’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2270:12: note: ‘platform_profile_victus_get’ declared here
>  2270 | static int platform_profile_victus_get(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2703:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
>  2703 |         .profile_set = platform_profile_victus_set,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2703:24: note: (near initialization for ‘platform_profile_victus_handler.profile_set’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2508:12
When using updater inside program it fails to update because cant find an omen-space directory with setup file.: note: ‘platform_profile_victus_set’ declared here
>  2508 | static int platform_profile_victus_set(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2707:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
>  2707 |         .profile_get = platform_profile_omen_get,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2707:24: note: (near initialization for ‘platform_profile_victus_s_handler.profile_get’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2029:12: note: ‘platform_profile_omen_get’ declared here
>  2029 | static int platform_profile_omen_get(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2708:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
>  2708 |         .profile_set = platform_profile_victus_s_set,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2708:24: note: (near initialization for ‘platform_profile_victus_s_handler.profile_set’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2493:12: note: ‘platform_profile_victus_s_set’ declared here
>  2493 | static int platform_profile_victus_s_set(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2712:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
>  2712 |         .profile_get = hp_wmi_platform_profile_get,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2712:24: note: (near initialization for ‘hp_wmi_platform_profile_handler.profile_get’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2178:12: note: ‘hp_wmi_platform_profile_get’ declared here
>  2178 | static int hp_wmi_platform_profile_get(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2713:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
>  2713 |         .profile_set = hp_wmi_platform_profile_set,
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2713:24: note: (near initialization for ‘hp_wmi_platform_profile_handler.profile_set’)
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2207:12: note: ‘hp_wmi_platform_profile_set’ declared here
>  2207 | static int hp_wmi_platform_profile_set(struct device *dev,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:2523:12: warning: ‘hp_wmi_platform_profile_probe’ defined but not used [-Wunused-function]
>  2523 | static int hp_wmi_platform_profile_probe(void *drvdata,
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.c:537:29: warning: ‘platform_profile_device’ defined but not used [-Wunused-variable]
>   537 | static struct device       *platform_profile_device;
>       |                             ^~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/hp-omen-extra/2.0.3/build/hp-wmi.o] Error 1
> make[1]: *** [/usr/lib/modules/6.12.108-1-MANJARO/build/Makefile:1967: /var/lib/dkms/hp-omen-extra/2.0.3/build] Error 2
> make: *** [Makefile:224: __sub-make] Error 2
> make: Leaving directory '/usr/lib/modules/6.12.108-1-MANJARO/build'
> 
> # exit code: 2
> # elapsed time: 00:00:01
> ----------------------------------------------------------------
> 
### 
**[Bug] No such file or directory when trying to use in-app updater**
When using updater inside program it fails to update because it cant find an omen-space directory with setup file.
Here's the screenshot as proof:
<img width="1161" height="813" alt="Image" src="https://github.com/user-attachments/assets/ddcc447f-f90f-475c-a049-9533bd1e243c" />

**Comment by yunusemreyl** [comment]
Hello. Unfortunately, the update backend is broken in older versions. Please update using `sudo ./setup.sh update`.

**Comment by BananaShapedGrenade** [comment]
i used a curl command the same one for install and it done the magic because console kept saying that command was not found. Anyways, are those DKMS build errors are something important? because i keep getting them with each try to update or install, but after reboot everything seems fine and working.
