### ISSUE TITLE
[Build Failure] hp-rgb-lighting module fails to compile on Kernel 7.1.3 (symbol_get/mutex issue)

### ISSUE THREAD

**Issue by Pulla32** [yunusemreyl/OmenCommandCenterforLinux#130]
Following up on the build failure on Kernel 7.1.3-2-cachyos-bore. I have investigated the make.log and confirmed that this is an architecture-level incompatibility with newer kernels.

The Problem:
The build fails with error: 'hp_wmi_mutex' undeclared. In kernels 7.0+, this symbol is no longer exported to the kernel symbol table, making symbol_get() calls ineffective. Even when attempting to bypass this, the driver cannot reach the required memory addresses, which explains why the RGB control fails even if compilation is forced.

Environment:
    Kernel: 7.1.3-2-cachyos-bore
    Laptop Model: OMEN Laptop 15-ek0xxx
    Board: 8BCD

Suggested Path Forward:
The driver needs to transition from relying on symbol_get() for internal mutexes to using the official hp_wmi_perform_query API, which is the standard, thread-safe way to communicate with HP hardware on modern kernels.

Build Log:
hp-rgb-lighting.c: Funktio ”_get_wmi_mutex”:
hp-rgb-lighting.c:105:62: error: ”hp_wmi_mutex” undeclared (first use in this function); did you mean ”_get_wmi_mutex”?
  105 |                 struct mutex *m = (struct mutex *)symbol_get(hp_wmi_mutex);
      |                                                              ^~~~~~~~~~~~
/usr/lib/modules/7.1.3-2-cachyos-bore/build/include/linux/module.h:597:18: note: in definition of macro ”symbol_get”
  597 |         (typeof(&x))(__symbol_get(__stringify(x))); })
      |                  ^
hp-rgb-lighting.c:105:62: note: each undeclared identifier is reported only once for each function it appears in.

I have also verified via /proc/kallsyms that hp_wmi_mutex is not present in the exported symbol table of my current kernel (7.1.3-2-cachyos-bore), which confirms that it is unreachable by the module.

**Comment by yunusemreyl** [comment]
It should be fixed now. 

```bash
cd OmenCtl
git pull
sudo ./setup.sh update
```

**Comment by Pulla32** [comment]
Thank you for the quick fix! Unfortunately, it's not building yet. The previous hp_wmi_mutex error is gone, but now I'm getting a linkage error in the modpost phase:

ERROR: modpost: "hp_wmi_perform_query" [hp-rgb-lighting.ko] undefined!

It seems that while the code now calls the correct function, the module is not linking against the hp-wmi core module where hp_wmi_perform_query resides. On my kernel (7.1.3-2-cachyos-bore), the hp-wmi driver might not be exposing this symbol to external modules in the way the driver expects.

Here is the latest make.log error output:

ERROR: modpost: "hp_wmi_perform_query" [hp-rgb-lighting.ko] undefined!
make[3]: *** [/usr/lib/modules/7.1.3-2-cachyos-bore/build/scripts/Makefile.modpost:147: Module.symvers] Error 1
make[2]: *** [/usr/lib/modules/7.1.3-2-cachyos-bore/build/Makefile:2120: modpost] Error 2
make[1]: *** [/usr/lib/modules/7.1.3-2-cachyos-bore/build/Makefile:248: __sub-make] Error 2
make[1]: Leaving directory '/var/lib/dkms/hp-rgb-lighting/1.6.5/build'
make: *** [Makefile:248: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/7.1.3-2-cachyos-bore/build'
```"

**Comment by yunusemreyl** [comment]
"Hey, thanks for testing and reporting this!

The modpost error happens because hp_wmi_perform_query is an internal (static) function in the mainline hp-wmi module, so it isn't exported for external modules like ours to link against. Since we want the hp-rgb-lighting module to work seamlessly alongside the stock hp-wmi kernel driver (like the one in CachyOS), we can't rely on those internal functions.

To fix this, I've just updated hp-rgb-lighting.c to include its own standalone WMI query logic. It now calls the standard wmi_evaluate_method() directly and uses its own local mutex, completely decoupling it from the core hp-wmi driver.

It should compile cleanly on your kernel now without any linkage errors. Could you pull the latest changes and give the build another try? Let me know how it goes!"

**Comment by Pulla32** [comment]
Hi, I have been testing the latest main branch (commit [ab5348e]). Here is my report on the progress and the remaining issues:

1. Driver Build (Success)
The previous linkage errors are resolved! The hp-rgb-lighting driver now builds successfully via DKMS and loads into the kernel.

2. Manual Fixes Applied (For your info)
To get the services running, I had to manually apply two fixes:

    Systemd Permissions: I had to set User=root in both hpm-platform.service and hpm-rgb.service to prevent "Root privileges required" errors.

    Syntax Error: There was a SyntaxError: unexpected character after line continuation character in /usr/libexec/hp-manager/services/rgb_service.py at line 216. I removed the stray backslash (\) to fix the syntax.

3. Remaining Issue: Platform Service Crash
After the fixes above, hpm-rgb.service is now active (running), but the keyboard LEDs are off and not responding. The hpm-platform.service is crashing with a critical error, which is likely preventing the RGB controller from initializing:

2026-07-16 21:46:48,820 [platform] [CRITICAL] [platform] Service error: Argument 0 does not allow None as a value

Here is the full log for the platform service:

[2026-07-16 21:46:48,787 [platform] [INFO] Matched board ID 878A in capabilities database
2026-07-16 21:46:48,788 [platform] [INFO] Trying to load ec_sys kernel module with write_support=1...
2026-07-16 21:46:48,797 [platform] [INFO] Starting Macro listener thread...
2026-07-16 21:46:48,820 [platform] [INFO] [platform] Sleep/wake handler registered
2026-07-16 21:46:48,820 [platform] [CRITICAL] [platform] Service error: Argument 0 does not allow None as a value: sudo /usr/bin/python3 /usr/libexec/hp-manager/services/platform_service.py]

It seems the platform service is hitting a None value during initialization. Could this be related to how the board ID is being handled, or is it preventing the RGB controller from receiving the signal to turn on?

Thank you for the quick work on the kernel driver!

**Comment by Pulla32** [comment]
Update:
I have noticed that other users are reporting the exact same Argument 0 does not allow None as a value error on their devices (e.g., in Issue #131). This confirms that this is a systemic issue in how the platform service handles Board ID identification and initialization. Since the RGB service is now running on my end after the manual fixes, it is clear that the platform service crash is the final bottleneck preventing the RGB controller from receiving signals. I hope this helps in tracking down the root cause!

**Comment by yunusemreyl** [comment]
Hello thank u for ur important feedback.
its fixed now. if problem persists u can open new issue.
