### ISSUE TITLE
Fan control (Auto/Performance/Custom) non-functional on Board 8E35 due to broken ACPI WMI methods (WQBZ/WQBE)

### ISSUE THREAD

**Issue by NorthSimon** [yunusemreyl/OmenCommandCenterforLinux#110]
Issue with the help of Claude AI

## System Information
- **Model:** HP OMEN Gaming Laptop 16-ap0044nf
- **Board ID:** 8E35
- **BIOS Version:** F.13 Rev.A (latest available as of July 2026, released 05/22/2026)
- **OS:** Fedora 44 KDE Plasma
- **Kernel:** 7.0.14-201.fc44.x86_64
- **CPU:** AMD Ryzen 9 8940HX
- **GPU:** NVIDIA RTX 5060 Laptop
- **OmenCtl version:** Latest (installed via setup.sh, without custom fan driver — script auto-detected kernel ≥7.0 and skipped it)

## Issue Summary
Fan control modes Auto, Performance, and Custom are non-functional. Only Max/Boost mode works. This appears to be caused by broken ACPI methods in the BIOS firmware, not an OmenCtl or driver bug.

## Detailed Behavior (tested with hpm-fan service running)

| Mode selected in UI | `pwm1_enable` value | Fan RPM behavior | Result |
|---|---|---|---|
| Max | Changes to `0` | Ramps to full speed | ✅ Works |
| Auto | Stays at `2` | Fixed ~2500 RPM, no dynamic response to load | ⚠️ No real regulation — just firmware default idle state |
| Performance | Stays at `2` | Identical to Auto, no change | ❌ No effect |
| Custom curve | N/A | N/A | ❌ Not available in UI (no `pwm1` duty file exposed) |

## Root Cause (confirmed via dmesg)
ACPI Error: Aborting method _SB.WMID.WQBZ due to previous error (AE_AML_BUFFER_LIMIT) (20251212/psparse-529)
ACPI Error: Aborting method _SB.WMID.WQBE due to previous error (AE_AML_BUFFER_LIMIT) (20251212/psparse-529)
These errors occur at every boot, before any OmenCtl service starts. This confirms the WMI query methods responsible for thermal profile control fail at the firmware level.

## Sysfs State
/sys/class/hwmon/hwmonX/ (name: hp, device -> hp-wmi)
fan1_input   (read-only, works)
fan2_input   (read-only, works)
pwm1_enable  (read-write, binary toggle only: 0=boost, 2=auto)
→ no pwm1 (duty cycle) file exposed
→ no platform_profile in /sys/firmware/acpi/

## Additional Testing
- Tested identical behavior on **both Fedora 44 and Kubuntu/Ubuntu** — confirms this is not distro-specific.
- Installed `hp-rgb-lighting` driver via DKMS + MOK (Secure Boot remained enabled throughout) — RGB control now works correctly, but had **zero effect** on fan control, as expected since it's a separate subsystem.
- Confirmed via `pelrun/hp-omen-linux-module` issue #38 that board 8E35 is already listed in `omen_thermal_profile_boards`, but full profile control still appears blocked by these ACPI failures.
- No existing report found for this specific `WQBZ`/`WQBE` error on board 8E35 (distinct from the `_SB.PEP.DETY` issue reported for board 8BCA).

## Question for maintainer
Given that this appears to be a firmware-level ACPI bug (not fixable in userspace), is there any known EC-level fallback (direct register access, similar to the 0x11 fallback added for board 17-cb1xxx) that could bypass the broken WMI methods for board 8E35? Happy to test on real hardware if a patch/branch is available.

**Comment by yunusemreyl** [comment]
Hello, thank you very much for your reply. Could you try the 1.6.3 update and send me the dumps from the application's settings page?

**Comment by NorthSimon** [comment]
After updating to v1.6.3, which specifically targets board 8E35 with a new EC fallback mechanism (offset 0x59, writing profile values 0x31/0x30), the fallback never activates. Fan control behavior is identical to before the update: only Auto and Max modes work.

## Root Cause (from journalctl)

**hpm-power.service crashes during profile restore:**
File "/usr/libexec/hp-manager/services/power_service.py", line 409, in _delayed_profile_restore
self._ctrl._sync_hardware_power(saved)
File "/usr/libexec/hp-manager/services/power_service.py", line 299, in _sync_hardware_power
self.ec.set_perf_mode(profile)
AttributeError: 'PowerProfileController' object has no attribute 'ec'
The `ec` attribute on `PowerProfileController` is never set — it looks like the EC fallback object either fails silently during init or is never instantiated for this board, despite 8E35 being the explicit target of this release.

## Consequence on fan control

Since the EC path was never initialized, hpm-fan.service falls back to the old sysfs method, which fails exactly as before the update:
SetFanMode: performance
sysfs_write /sys/class/hwmon/hwmon7/pwm1_enable=1 error: [Errno 95] Operation not supported
Failed to set fan mode to performance (all paths failed)

## Current behavior
| Mode | Result |
|---|---|
| Auto | Works (firmware default, fixed ~2500 RPM) |
| Max | Works (`pwm1_enable=0`) |
| Performance | Fails — "all paths failed" |
| Balanced | Not tested individually but expected to fail the same way |
| Custom | Not available in UI |

## Reference — ACPI errors still present (expected, unrelated to this bug)
ACPI Error: Aborting method _SB.WMID.WQBZ due to previous error (AE_AML_BUFFER_LIMIT)
ACPI Error: Aborting method _SB.WMID.WQBE due to previous error (AE_AML_BUFFER_LIMIT)
These are the original firmware-level errors the EC fallback in v1.6.3 is meant to bypass — they're still present, but that's expected since the bypass itself never activates.

## Request
Could you check the initialization path for `PowerProfileController.ec` on board 8E35? It seems the object is either not created, or created conditionally on something that fails silently before reaching `_sync_hardware_power`. Happy to add debug logging and test a patch if useful — I have consistent, reproducible access to this hardware.

Thanks for the quick turnaround on the 8E35-specific release, really appreciate the responsiveness!

**Comment by yunusemreyl** [comment]
4. Power Profile Fallback Crash Fix (power_service.py)
   - Resolved AttributeError when triggering EC fallback on boards with broken WMI (e.g. 8E35).
   - Updated PowerProfileController to properly accept and initialize the ec_controller argument.
   - Restores Performance and Custom fan control modes on affected boards.
Can u check?

**Comment by NorthSimon** [comment]
> 4. Power Profile Fallback Crash Fix (power_service.py)
>    
>    * Resolved AttributeError when triggering EC fallback on boards with broken WMI (e.g. 8E35).
>    * Updated PowerProfileController to properly accept and initialize the ec_controller argument.
>    * Restores Performance and Custom fan control modes on affected boards.
>      Can u check?

On a HP Omen 16 (board 8E35, HP OMEN MAX 16t-ah000), the Performance and Custom fan modes consistently fail with [Errno 95] Operation not supported when writing to pwm1_enable. Only Auto (pwm1_enable=2) and Max modes work correctly.

Environment


Model: HP Omen 16-ap0044nf / HP OMEN MAX 16t-ah000
Board ID: 8E35
CPU: AMD Ryzen 9 9840HX
GPU: NVIDIA RTX 5060 8 GB
BIOS: F.13
OS: Fedora 44 KDE
Kernel: 7.1.3-200.fc44.x86_64
OmenCtl: v1.6.4 (updated from v1.6.3 during this diagnostic)
Secure Boot: enabled (required for Battlefield 6 anti-cheat), hp-rgb-lighting DKMS module MOK-signed, no issues after updating to v1.6.4


Observed Behavior

1. Auto mode — working


pwm1_enable = 2 (hardware thermostat)
Responsive to load/temperature
Correctly triggers "Thermal Protection" mode (max fan) above 95 °C, and reverts below 77 °C


2. Max mode — working


pwm1_enable = 2, pwm1 = 255
Measured peak RPM: ~4800–5000 RPM (fan1/fan2), so actual hardware capability is well above the RPM seen under Auto at moderate load (~2600–2800 RPM)


3. Performance mode — consistent failure

Logs from journalctl -u hpm-fan.service:

[fan] [INFO] SetFanMode: performance
[fan] [ERROR] sysfs_write /sys/class/hwmon/hwmon7/pwm1_enable=1 error: [Errno 95] Operation not supported
[fan] [WARNING] Failed to set fan mode to performance (all paths failed)

Repeats for every attempt (including SetFanTarget with a target RPM), same Errno 95 every time. The kernel outright rejects writing pwm1_enable=1 (manual mode) on this hwmon.

4. Custom mode — not exposed in UI

Source code investigation (src/):

python# capabilities.py
"8E35": ModelCapabilities("8E35", "OMEN MAX 16t-ah000", model_year=2025,
    family="OMEN", has_mux_switch=True, supports_fan_control_ec=False)

supports_fan_control_ec=False causes fan_service.py::supports_custom_mode() to return False, which hides the custom button in fan_page.py (fan_control_custom_btn.set_visible(supports_custom)). Consistent with the Performance mode failure observed above (same underlying sysfs mechanism).

Diagnostic History (useful context)


After a BIOS reflash, the setup.sh script in the driver/ folder misidentified kernel 7.0.14 as "below 7.0" (likely a version-comparison bug not accounting for the 6.19 → 7.0 rollover), and installed a custom hp-wmi.ko.xz out-of-tree (/lib/modules/.../extra/, not owned by any RPM package), causing fan speed capping and a forced "custom" mode at boot.
Resolved by upgrading to kernel 7.1.3 (the orphaned custom module was removed, replaced by the stock module shipped in kernel-modules-7.1.3-200.fc44).
A leftover config file /etc/hp-manager/fan.json was stuck on "fan_mode": "max" with "custom_curve": "[]" — likely left over from an earlier test session, manually reset to "auto".
Updated to v1.6.4 specifically for the announced fix:

Power Profile Fallback Crash Fix — Resolved AttributeError when triggering EC fallback on boards with broken WMI (e.g. 8E35).



This fix does resolve the AttributeError: 'PowerProfileController' has no attribute 'ec' crash on the power_service.py side (confirmed — PowerProfileController: Using Tuned backend now starts cleanly). However, it does not resolve the sysfs pwm1_enable=1 rejection on the fan_service.py side, which appears to be a separate issue.


Additional Detail — Sleep Handler

Recurring warning at startup for both services, not directly related to the main issue but possibly worth noting:

[fan] [WARNING] Failed to register sleep handler: g-dbus-error-quark: 
GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Unknown object '/org/freedesktop/login1/Manager'. (41)

Practical consequence: after suspend/resume, fans stay stuck at their last state until a manual mode change is triggered — the service doesn't receive the resume event.

Questions for the Developer


Is supports_fan_control_ec=False on 8E35 documenting a confirmed permanent hardware limitation (EC permanently rejecting pwm1_enable=1), or a temporary limitation pending an alternative control method (e.g. direct AML/ACPI calls instead of standard sysfs)?
Is there a possible workaround similar to the EC fallback already implemented for power profiles (ec_controller.py, offset 0x59), but applied to fan control instead of the thermal profile?
The D-Bus sleep handler (/org/freedesktop/login1/Manager) — the object path/interface may be incorrect, or login1 may not be reachable from the service's context; possibly a simple fix if useful.


Full logs available on request

journalctl -u hpm-fan.service -u hpm-power.service covering the test session (Auto → Performance → Max attempts).

**Comment by yunusemreyl** [comment]
Hello, thanks again for the incredibly detailed diagnostics and for offering to test on your hardware. I’ve looked into all three issues you raised and pushed a few updates to address them.

1. Logind D-Bus Sleep Handler Error You were completely right about this being an object path introspection issue. pydbus was automatically trying to construct a proxy object and failing to introspect the Manager interface properly. I've refactored dbus_helpers.py to use a direct raw bus.subscribe() for the PrepareForSleep signal, which bypasses the proxy object entirely. The suspend/resume fan state restoration should now work without throwing that UnknownObject error.

2. Performance Mode via EC Fallback The EC fallback for thermal profiles via offset 0x59 is indeed intended to bypass the broken WMI methods on 8E35. The reason fan_service.py was still failing with [Errno 95] on Performance mode is because it had a safety check (not self.ec.is_unsafe_ec_model) that inadvertently blocked all EC operations on your board, including the safe thermal profile fallback. I've loosened this restriction, so clicking "Performance" in the UI will now successfully write 0x31 to offset 0x59 via the EC, correctly enabling Performance mode even without pwm1_enable=1.

3. Custom Mode & EC Hardware Limitation Test Regarding your question about supports_fan_control_ec=False: This is an intentional safety lock. On most 2024+ Intel and AMD boards, the legacy EC fan curve registers (0x2E and 0x2F) are unsupported, and attempting to write to them can cause the Embedded Controller to panic and hard-lock the system. Because the kernel also rejects pwm1_enable=1 due to the AE_AML_BUFFER_LIMIT ACPI bug, Custom mode is deliberately hidden to protect the hardware.

However, since you explicitly offered to test a workaround on real hardware, I’ve decided to unlock it for your specific board! I've updated the 8E35 profile in capabilities.py to supports_fan_control_ec=True.

This means the "Custom" mode button will now appear in your UI. When you apply a custom curve, the service will attempt to directly manipulate the fans via the legacy EC registers as a fallback for the sysfs failure.

⚠️ Important Warning for your Test: If the legacy EC registers are truly incompatible with the 8E35 hardware, applying a Custom curve might cause the EC to panic (the fans might stop spinning entirely, ramp to 100%, or the laptop might suddenly power off). **If this happens, do not panic—just perform a hard reset by holding your laptop's power button down for 15-20 seconds to clear the EC state.**

Please pull the latest changes, restart the hpm-fan and hpm-power services, and let me know how the test goes. If the direct EC fan control actually works on 8E35 without crashing, that would be a huge win!

**Comment by NorthSimon** [comment]
> Hello, thanks again for the incredibly detailed diagnostics and for offering to test on your hardware. I’ve looked into all three issues you raised and pushed a few updates to address them.
> 
> 1. Logind D-Bus Sleep Handler Error You were completely right about this being an object path introspection issue. pydbus was automatically trying to construct a proxy object and failing to introspect the Manager interface properly. I've refactored dbus_helpers.py to use a direct raw bus.subscribe() for the PrepareForSleep signal, which bypasses the proxy object entirely. The suspend/resume fan state restoration should now work without throwing that UnknownObject error.
> 2. Performance Mode via EC Fallback The EC fallback for thermal profiles via offset 0x59 is indeed intended to bypass the broken WMI methods on 8E35. The reason fan_service.py was still failing with [Errno 95] on Performance mode is because it had a safety check (not self.ec.is_unsafe_ec_model) that inadvertently blocked all EC operations on your board, including the safe thermal profile fallback. I've loosened this restriction, so clicking "Performance" in the UI will now successfully write 0x31 to offset 0x59 via the EC, correctly enabling Performance mode even without pwm1_enable=1.
> 3. Custom Mode & EC Hardware Limitation Test Regarding your question about supports_fan_control_ec=False: This is an intentional safety lock. On most 2024+ Intel and AMD boards, the legacy EC fan curve registers (0x2E and 0x2F) are unsupported, and attempting to write to them can cause the Embedded Controller to panic and hard-lock the system. Because the kernel also rejects pwm1_enable=1 due to the AE_AML_BUFFER_LIMIT ACPI bug, Custom mode is deliberately hidden to protect the hardware.
> 
> However, since you explicitly offered to test a workaround on real hardware, I’ve decided to unlock it for your specific board! I've updated the 8E35 profile in capabilities.py to supports_fan_control_ec=True.
> 
> This means the "Custom" mode button will now appear in your UI. When you apply a custom curve, the service will attempt to directly manipulate the fans via the legacy EC registers as a fallback for the sysfs failure.
> 
> ⚠️ Important Warning for your Test: If the legacy EC registers are truly incompatible with the 8E35 hardware, applying a Custom curve might cause the EC to panic (the fans might stop spinning entirely, ramp to 100%, or the laptop might suddenly power off). **If this happens, do not panic—just perform a hard reset by holding your laptop's power button down for 15-20 seconds to clear the EC state.**
> 
> Please pull the latest changes, restart the hpm-fan and hpm-power services, and let me know how the test goes. If the direct EC fan control actually works on 8E35 without crashing, that would be a huge win!

Thanks for the fixes! Bad news on my end though — I found the actual root cause, and it's not something fixable in OmenCtl's code.

## Root cause: Kernel Lockdown (Secure Boot) blocks ec_sys write_support

I have Secure Boot enabled (required for BF6 anti-cheat on my Windows dual-boot). Testing the `ec_sys` module load manually:
$ sudo modprobe ec_sys write_support=1
modprobe: ERROR: could not insert 'ec_sys': Operation not permitted
$ cat /sys/kernel/security/lockdown
none [integrity] confidentiality

Kernel lockdown is in `integrity` mode (enabled automatically by Secure Boot on Fedora), which explicitly blocks `ec_sys` with `write_support=1` since it allows arbitrary memory writes — this is a known, intentional kernel security restriction, not a bug.

## Why this explains everything

In `ec_controller.py`, `has_ec_access` depends on `os.path.exists(EC_PATH)` (`/sys/kernel/debug/ec/ec0/io`), which only exists if `ec_sys` loaded successfully. Since the modprobe fails silently (only logged at `debug` level), `has_ec_access` stays `False`, so every EC fallback path (`set_perf_mode`, Custom mode, etc.) is a no-op regardless of the `is_unsafe_ec_model`/`supports_fan_control_ec` fixes — "all paths failed" was accurate, just for a different reason than expected.

## Suggestion

Might be worth:
1. Logging the `modprobe` failure at `warning`/`error` level instead of `debug`, so users with Secure Boot don't waste time thinking it's a code bug
2. Detecting lockdown state (`/sys/kernel/security/lockdown`) at startup and surfacing a clear message in the UI/logs ("EC fallback unavailable: kernel lockdown active, likely due to Secure Boot")

For my specific case, this is an acceptable limitation — I'd rather keep Secure Boot on for anti-cheat than get finer fan control. Just wanted to document this clearly in case other 8E35/8A43 users with Secure Boot hit the same wall. Thanks again for all the work on this, and sorry for the dead end!
