### ISSUE TITLE
Diagnostic Report

### ISSUE THREAD

**Issue by BananaShapedGrenade** [yunusemreyl/OmenCommandCenterforLinux#187]
# OMENSpace Diagnostic Report

> Generated: 2026-09-07 01:10:50

## Environment

| Field | Value |
|-------|-------|
| OMENSpace version | `2.0.0` |
| OS              | `Manjaro Linux  ·  Linux 6.12.104-1-MANJARO` |
| Kernel          | `6.12.104-1-MANJARO` |

## Hardware Probe

| Field | Value |
|-------|-------|
| Manufacturer | `HP` |
| Product ID   | `8A43` |
| BIOS Version | `F.26` |
| CPU          | `AMD Ryzen 7 6800H with Radeon Graphics  ·  16 Threads` |
| GPU          | `NVIDIA GeForce RTX 3060 Laptop GPU  ·  6 GB GDDR6` |

## Live Fan Telemetry

- CPU Fan: 2629 RPM (Temp: 37 °C)
- GPU Fan: (Mapped to CPU RPM max) (Temp: 33 °C)

## EC Registers — Snapshot

```
EC Read failed. Debugfs not mounted or requires root/ec_sys.
```
So i got error during install of a new update
Here's the logs of another DKMS install error:
DKMS (dkms-3.4.1) make.log for hp-omen-extra/2.0.0 for kernel 6.12.104-1-MANJARO (x86_64)
Mon Sep  7 00:18:33 CEST 2026

Building module(s)
# command: grep -iq clang /proc/version && make LLVM=1 -C /usr/lib/modules/6.12.104-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.0/build EXTRA_CFLAGS='' modules || make -C /usr/lib/modules/6.12.104-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.0/build EXTRA_CFLAGS='' modules
make: Entering directory '/usr/lib/modules/6.12.104-1-MANJARO/build'
grep: dkms.conf: No such file or directory
grep: dkms.conf: No such file or directory
  CC [M]  /var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.o
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2500:21: error: variable ‘platform_profile_omen_ops’ has initializer but incomplete type
 2500 | static const struct platform_profile_ops platform_profile_omen_ops = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2501:10: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2501 |         .probe       = hp_wmi_platform_profile_probe,
      |          ^~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2501:24: warning: excess elements in struct initializer
 2501 |         .probe       = hp_wmi_platform_profile_probe,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2501:24: note: (near initialization for ‘platform_profile_omen_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2502:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2502 |         .profile_get = platform_profile_omen_get,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2502:24: warning: excess elements in struct initializer
 2502 |         .profile_get = platform_profile_omen_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2502:24: note: (near initialization for ‘platform_profile_omen_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2503:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2503 |         .profile_set = platform_profile_omen_set,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2503:24: warning: excess elements in struct initializer
 2503 |         .profile_set = platform_profile_omen_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2503:24: note: (near initialization for ‘platform_profile_omen_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2506:21: error: variable ‘platform_profile_victus_ops’ has initializer but incomplete type
 2506 | static const struct platform_profile_ops platform_profile_victus_ops = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2507:10: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2507 |         .probe       = hp_wmi_platform_profile_probe,
      |          ^~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2507:24: warning: excess elements in struct initializer
 2507 |         .probe       = hp_wmi_platform_profile_probe,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2507:24: note: (near initialization for ‘platform_profile_victus_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2508:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2508 |         .profile_get = platform_profile_victus_get,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2508:24: warning: excess elements in struct initializer
 2508 |         .profile_get = platform_profile_victus_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2508:24: note: (near initialization for ‘platform_profile_victus_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2509:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2509 |         .profile_set = platform_profile_victus_set,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2509:24: warning: excess elements in struct initializer
 2509 |         .profile_set = platform_profile_victus_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2509:24: note: (near initialization for ‘platform_profile_victus_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2512:21: error: variable ‘platform_profile_victus_s_ops’ has initializer but incomplete type
 2512 | static const struct platform_profile_ops platform_profile_victus_s_ops = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2513:10: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2513 |         .probe       = hp_wmi_platform_profile_probe,
      |          ^~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2513:24: warning: excess elements in struct initializer
 2513 |         .probe       = hp_wmi_platform_profile_probe,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2513:24: note: (near initialization for ‘platform_profile_victus_s_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2514:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2514 |         .profile_get = platform_profile_omen_get,   /* uses cached value */
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2514:24: warning: excess elements in struct initializer
 2514 |         .profile_get = platform_profile_omen_get,   /* uses cached value */
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2514:24: note: (near initialization for ‘platform_profile_victus_s_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2515:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2515 |         .profile_set = platform_profile_victus_s_set,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2515:24: warning: excess elements in struct initializer
 2515 |         .profile_set = platform_profile_victus_s_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2515:24: note: (near initialization for ‘platform_profile_victus_s_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2518:21: error: variable ‘hp_wmi_platform_profile_ops’ has initializer but incomplete type
 2518 | static const struct platform_profile_ops hp_wmi_platform_profile_ops = {
      |                     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2519:10: error: ‘const struct platform_profile_ops’ has no member named ‘probe’
 2519 |         .probe       = hp_wmi_platform_profile_probe,
      |          ^~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2519:24: warning: excess elements in struct initializer
 2519 |         .probe       = hp_wmi_platform_profile_probe,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2519:24: note: (near initialization for ‘hp_wmi_platform_profile_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2520:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_get’
 2520 |         .profile_get = hp_wmi_platform_profile_get,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2520:24: warning: excess elements in struct initializer
 2520 |         .profile_get = hp_wmi_platform_profile_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2520:24: note: (near initialization for ‘hp_wmi_platform_profile_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2521:10: error: ‘const struct platform_profile_ops’ has no member named ‘profile_set’
 2521 |         .profile_set = hp_wmi_platform_profile_set,
      |          ^~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2521:24: warning: excess elements in struct initializer
 2521 |         .profile_set = hp_wmi_platform_profile_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2521:24: note: (near initialization for ‘hp_wmi_platform_profile_ops’)
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c: In function ‘thermal_profile_setup’:
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2597:17: error: implicit declaration of function ‘devm_platform_profile_register’; did you mean ‘platform_profile_register’? [-Wimplicit-function-declaration]
 2597 |                 devm_platform_profile_register(&device->dev, "hp-wmi", NULL, ops);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 platform_profile_register
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2596:33: error: assignment to ‘struct device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2596 |         platform_profile_device =
      |                                 ^
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c: At top level:
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2500:42: error: storage size of ‘platform_profile_omen_ops’ isn’t known
 2500 | static const struct platform_profile_ops platform_profile_omen_ops = {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2506:42: error: storage size of ‘platform_profile_victus_ops’ isn’t known
 2506 | static const struct platform_profile_ops platform_profile_victus_ops = {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2512:42: error: storage size of ‘platform_profile_victus_s_ops’ isn’t known
 2512 | static const struct platform_profile_ops platform_profile_victus_s_ops = {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.c:2518:42: error: storage size of ‘hp_wmi_platform_profile_ops’ isn’t known
 2518 | static const struct platform_profile_ops hp_wmi_platform_profile_ops = {
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/hp-omen-extra/2.0.0/build/hp-wmi.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.104-1-MANJARO/build/Makefile:1967: /var/lib/dkms/hp-omen-extra/2.0.0/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.104-1-MANJARO/build'

# exit code: 2
# elapsed time: 00:00:01
----------------------------------------------------------------

Next part probably useless

Im not sure if i should to write about other issues if dkms build error happened, because if failed install caused other issues they may be false-positive but anyways, maybe it will be useful i'm not a techie guy:
1) profiles probably still does not work (i ran Cyberpunk2077 built-in benchmark on eco and performance modes, average fps was like 0.5-1 Frame difference between two. I dont know if it can be counted as valid tool, sorry i dont have a professional software for it). In system monitoring tab mode is always displayed as balanced. After changing mode to any and then proceeding to close and re-open OmenSpace, performance is being Balanced. GPU  Temp and load does not display too.
2) After failed install the omen space daemon was disabled and turned off, so i tried to turn it on manually using systemctl to enable it and then start it. Anyways it's i guess works only for some time because tray do not work and after some time ui just closes by itself (not always). Here is systemctl log:
Sep 07 01:08:45 ManjaroOmen systemd[1]: Starting Omen Space — Unified Daemon (omen-space-daemon)...
Sep 07 01:08:47 ManjaroOmen systemd[1]: Started Omen Space — Unified Daemon (omen-space-daemon).
Sep 07 01:08:47 ManjaroOmen omen-space-daemon[890]: modprobe: FATAL: Module ec_sys not found in directory /lib/modules/6.12.104-1-MANJARO
Sep 07 01:20:10 ManjaroOmen systemd[1]: Stopping Omen Space — Unified Daemon (omen-space-daemon)...
Sep 07 01:20:10 ManjaroOmen systemd[1]: omen-space-daemon.service: Deactivated successfully.
Sep 07 01:20:10 ManjaroOmen systemd[1]: Stopped Omen Space — Unified Daemon (omen-space-daemon).
Sep 07 01:20:10 ManjaroOmen systemd[1]: omen-space-daemon.service: Consumed 7.165s CPU time over 11min 25.770s wall clock time, 59.2M memory peak.
3) Fan mode does not react to being changed back to Auto from max mode after turning on Max mode.  So it being “Abandon All Hope, Ye Who Enter Here” after clicking it.

**Comment by BananaShapedGrenade** [comment]
I guess it works now. Performance has improved, but im not sure if i should get worried about still DKMS build fails error during install.


Building module(s)...(bad exit status: 2)
Failed command:
grep -iq clang /proc/version && make LLVM=1 -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.2/build EXTRA_CFLAGS='' modules || make -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.2/build EXTRA_CFLAGS='' modules

Error! Bad return status for module build on kernel: 6.12.108-1-MANJARO (x86_64)
Consult /var/lib/dkms/hp-omen-extra/2.0.2/build/make.log for more information.
[ERROR] DKMS build failed. Check logs.

Here is the content of make.log file: 
DKMS (dkms-3.4.3) make.log for hp-omen-extra/2.0.2 for kernel 6.12.108-1-MANJARO (x86_64)
Mon Sep  7 13:31:43 CEST 2026

Building module(s)
# command: grep -iq clang /proc/version && make LLVM=1 -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.2/build EXTRA_CFLAGS='' modules || make -C /usr/lib/modules/6.12.108-1-MANJARO/build M=/var/lib/dkms/hp-omen-extra/2.0.2/build EXTRA_CFLAGS='' modules
make: Entering directory '/usr/lib/modules/6.12.108-1-MANJARO/build'
grep: dkms.conf: No such file or directory
grep: dkms.conf: No such file or directory
  CC [M]  /var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.o
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2697:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
 2697 |         .profile_get = platform_profile_omen_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2697:24: note: (near initialization for ‘platform_profile_omen_handler.profile_get’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2029:12: note: ‘platform_profile_omen_get’ declared here
 2029 | static int platform_profile_omen_get(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2698:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
 2698 |         .profile_set = platform_profile_omen_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2698:24: note: (near initialization for ‘platform_profile_omen_handler.profile_set’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2152:12: note: ‘platform_profile_omen_set’ declared here
 2152 | static int platform_profile_omen_set(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2702:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
 2702 |         .profile_get = platform_profile_victus_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2702:24: note: (near initialization for ‘platform_profile_victus_handler.profile_get’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2270:12: note: ‘platform_profile_victus_get’ declared here
 2270 | static int platform_profile_victus_get(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2703:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
 2703 |         .profile_set = platform_profile_victus_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2703:24: note: (near initialization for ‘platform_profile_victus_handler.profile_set’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2508:12: note: ‘platform_profile_victus_set’ declared here
 2508 | static int platform_profile_victus_set(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2707:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
 2707 |         .profile_get = platform_profile_omen_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2707:24: note: (near initialization for ‘platform_profile_victus_s_handler.profile_get’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2029:12: note: ‘platform_profile_omen_get’ declared here
 2029 | static int platform_profile_omen_get(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2708:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
 2708 |         .profile_set = platform_profile_victus_s_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2708:24: note: (near initialization for ‘platform_profile_victus_s_handler.profile_set’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2493:12: note: ‘platform_profile_victus_s_set’ declared here
 2493 | static int platform_profile_victus_s_set(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~


I tried to use newer kernel too, just to test and try if it's just on 
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2712:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option *)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option *)’ [-Wincompatible-pointer-types]
 2712 |         .profile_get = hp_wmi_platform_profile_get,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2712:24: note: (near initialization for ‘hp_wmi_platform_profile_handler.profile_get’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2178:12: note: ‘hp_wmi_platform_profile_get’ declared here
 2178 | static int hp_wmi_platform_profile_get(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2713:24: error: initialization of ‘int (*)(struct platform_profile_handler *, enum platform_profile_option)’ from incompatible pointer type ‘int (*)(struct device *, enum platform_profile_option)’ [-Wincompatible-pointer-types]
 2713 |         .profile_set = hp_wmi_platform_profile_set,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2713:24: note: (near initialization for ‘hp_wmi_platform_profile_handler.profile_set’)
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2207:12: note: ‘hp_wmi_platform_profile_set’ declared here
 2207 | static int hp_wmi_platform_profile_set(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:2523:12: warning: ‘hp_wmi_platform_profile_probe’ defined but not used [-Wunused-function]
 2523 | static int hp_wmi_platform_profile_probe(void *drvdata,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.c:537:29: warning: ‘platform_profile_device’ defined but not used [-Wunused-variable]
  537 | static struct device       *platform_profile_device;
      |                             ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:229: /var/lib/dkms/hp-omen-extra/2.0.2/build/hp-wmi.o] Error 1
make[1]: *** [/usr/lib/modules/6.12.108-1-MANJARO/build/Makefile:1967: /var/lib/dkms/hp-omen-extra/2.0.2/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.12.108-1-MANJARO/build'

# exit code: 2
# elapsed time: 00:00:01
------------------------------------------------------

I tried to use a newer kernel too, just in case if it works on newer versions. But after rebooting it would led to black screen. (Probably my user error)
